DROP DATABASE IF EXISTS acgndb;
CREATE DATABASE acgndb DEFAULT CHARACTER SET UTF8;
USE acgndb;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS zeroFlag;

CREATE TABLE user(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(16) NOT NULL DEFAULT '',
	pwd VARCHAR(32) NOT NULL DEFAULT '',
	auz INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '简单权限标识,默认0,没有权限'
)ENGINE = InnoDB DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;

CREATE TABLE zeroFlag(
	flag INT NOT NULL DEFAULT 0 COMMENT '表示是否初次使用,0 1'
)ENGINE = InnoDB DEFAULT CHARSET = utf8;
INSERT INTO zeroFlag(flag) VALUES(0);

SELECT * FROM zeroFlag;
SELECT * FROM user;